PGPASSWORD=${CLOUDRON_POSTGRESQL_PASSWORD} psql -h ${CLOUDRON_POSTGRESQL_HOST} -p ${CLOUDRON_POSTGRESQL_PORT} -U ${CLOUDRON_POSTGRESQL_USERNAME} \
 -d ${CLOUDRON_POSTGRESQL_DATABASE} -c "INSERT into t_config (cfg_id_c, cfg_value_c) \
VALUES('LDAP_ENABLED', true), ('LDAP_HOST', '$CLOUDRON_LDAP_SERVER'), \
('LDAP_PORT', $CLOUDRON_LDAP_PORT), ('LDAP_ADMIN_DN', '$CLOUDRON_LDAP_BIND_DN'), \
('LDAP_ADMIN_PASSWORD', '$CLOUDRON_LDAP_BIND_PASSWORD'), \
('LDAP_BASE_DN', '$CLOUDRON_LDAP_USERS_BASE_DN'), \
('LDAP_DEFAULT_EMAIL', 'mail@mail.com'), \
('LDAP_FILTER', '(objectclass=user)(|(USERNAME=%uid)(USERNAME=%uid)))'), \
('LDAP_DEFAULT_STORAGE', 1024000000), ('SMTP_FROM', '$CLOUDRON_MAIL_FROM');"